name: Periodic health check

on:
  push:
    branches:
      - main
    
jobs:
  periodic_health_check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: jtalk/url-health-check-action@v4
        with:
            url: https://full-stack-open-pokedex-jjunnila.onrender.com/