name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  CONDITION: ${{ github.event_name == 'push' && !contains(join(toJson(github.event.commits.*.message)), '#skip')}}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - run: npm run eslint
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
      - name: Trigger deployment
        if: ${{ env.CONDITION == 'true' }}
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      - name: Discord Webhook Notify Success
        uses: rjstone/discord-webhook-notify@v1.0.2
        if: success()
        with:
            severity: info
            text: A new version of Pokedex deployed
            description: to https://full-stack-open-pokedex-jjunnila.onrender.com/ by ${{ github.event.head_commit.committer.username }}
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      - name: Discord Webhook Notify Failure
        uses: rjstone/discord-webhook-notify@v1.0.2
        if: failure()
        with:
            severity: error
            text: Build failed!
            description: commit ${{ github.event.head_commit.url }} by ${{ github.event.head_commit.committer.username }} broke the build :(
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ env.CONDITION == 'true' }}
        uses: anothrNick/github-tag-action@f278d49d30cdd8775cc3e7dd00b5ee11686ee297
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
